### ISSUE TITLE
Support block content

### ISSUE THREAD

**Issue by danielblignaut** [sanity-io/sanity-plugin-mux-input#25]
Hi,

The Mux input works as a field on a custom document type however if I try adding it to the blockContent definition as a custom input, I get the following error:

Stack trace:
```
TypeError: this._input.focus is not a function
    at WithDocument.focus (/static/js/app.bundle.js:70760:19)
    at WithDocument.focus (/static/js/app.bundle.js:350865:25)
    at FormBuilderInput.focus (/static/js/app.bundle.js:39204:19)
    at FormBuilderInput.focus (/static/js/app.bundle.js:350865:25)
    at FormBuilderInput.componentDidMount (/static/js/app.bundle.js:39164:12)
    at FormBuilderInput.componentDidMount (/static/js/app.bundle.js:350855:123)
    at commitLifeCycles (/static/js/vendor.bundle.js:22535:22)
    at commitLayoutEffects (/static/js/vendor.bundle.js:25524:7)
    at HTMLUnknownElement.callCallback (/static/js/vendor.bundle.js:2909:14)
    at Object.invokeGuardedCallbackDev (/static/js/vendor.bundle.js:2958:16)

```
Component stack:
```
    in FormBuilderInput (created by DefaultObjectEditing)
    in div (created by ForwardRef(RegionsWithIntersections))
    in div (created by ForwardRef(RegionsWithIntersections))
    in ForwardRef(RegionsWithIntersections) (created by StickyOverlay)
    in StickyOverlay (created by OverlayEnabled)
    in Tracker (created by OverlayEnabled)
    in OverlayEnabled (created by DefaultObjectEditing)
    in div (created by DefaultDialogChildren)
    in div (created by ForwardRef(ScrollContainer))
    in ForwardRef(ScrollContainer) (created by DefaultDialogChildren)
    in div (created by DefaultDialogChildren)
    in div (created by DefaultDialogChildren)
    in div (created by ContainerQuery)
    in ContainerQuery (created by DefaultDialogChildren)
    in DefaultDialogChildren (created by DefaultDialog)
    in div (created by LayerChildren)
    in LayerChildren (created by Layer)
    in Portal (created by Layer)
    in LayerProvider (created by Layer)
    in Layer (created by DefaultDialog)
    in DefaultDialog (created by DefaultObjectEditing)
    in DefaultObjectEditing (created by EditObject)
    in EditObject (created by PortableTextInput)
    in BoundaryElementProvider (created by PortableTextInput)
    in div (created by PortableTextInput)
    in PortableTextInput (created by ForwardRef(PortableTextInput))
    in PortableTextEditor (created by ForwardRef(PortableTextInput))
    in ForwardRef(PortableTextInput) (created by PortableTextInputWithFocusAndBlur)
    in div (created by DefaultFormField)
    in div (created by DefaultFormField)
    in DefaultFormField (created by PortableTextInputWithFocusAndBlur)
    in PortableTextInputWithFocusAndBlur (created by withPatches(PortableTextInputWithFocusAndBlur))
    in withPatches(PortableTextInputWithFocusAndBlur) (created by FormBuilderInput)
    in ChangeIndicatorProvider (created by FormBuilderInput)
    in div (created by FormBuilderInput)
    in FormBuilderInput (created by Field)
    in div (created by Field)
    in Field (created by ObjectInput)
    in div (created by ObjectInput)
    in div (created by ObjectInput)
    in ObjectInput (created by FormBuilderInput)
    in ChangeIndicatorProvider (created by FormBuilderInput)
    in div (created by FormBuilderInput)
    in FormBuilderInput (created by SanityFormBuilder)
    in FormBuilderContext (created by SanityFormBuilderContext)
    in SanityFormBuilderContext (created by SanityFormBuilder)
    in SanityFormBuilder
    in form
    in Unknown (created by FormView)
    in div (created by ForwardRef(RegionsWithIntersections))
    in div (created by ForwardRef(RegionsWithIntersections))
    in ForwardRef(RegionsWithIntersections) (created by StickyOverlay)
    in StickyOverlay (created by OverlayEnabled)
    in Tracker (created by OverlayEnabled)
    in OverlayEnabled (created by FormView)
    in div (created by FormView)
    in FormView (created by DocumentPanel)
    in div (created by ForwardRef(ScrollContainer))
    in ForwardRef(ScrollContainer) (created by DocumentPanel)
    in div (created by DocumentPanel)
    in PortalProvider (created by DocumentPanel)
    in div (created by DocumentPanel)
    in DocumentPanel (created by DocumentPane)
    in div (created by DocumentPane)
    in div (created by ForwardRef(ScrollContainer))
    in ForwardRef(ScrollContainer) (created by EnabledChangeConnectorRoot)
    in Tracker (created by EnabledChangeConnectorRoot)
    in EnabledChangeConnectorRoot (created by DocumentPane)
    in div (created by KeyboardShortcutResponder)
    in KeyboardShortcutResponder (created by GetHookCollectionState)
    in GetHookCollectionState (created by RenderActionCollectionState)
    in RenderActionCollectionState
    in Unknown (created by DocumentPane)
    in DocumentPane (created by DocumentPaneProvider)
    in DocumentHistoryProvider (created by DocumentPaneProvider)
    in DocumentPaneProvider
    in StreamingComponent
    in StreamingComponent (created by Context.Consumer)
    in WithInitialValueWrapper (created by DeskToolPane)
    in DeskToolPane (created by DeskToolPanes)
    in SplitPaneWrapper (created by DeskToolPanes)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in PanesSplitController (created by DeskToolPanes)
    in div (created by DeskToolPanes)
    in DeskToolPanes (created by DeskTool)
    in DeskTool (created by withRouter(DeskTool))
    in withRouter(DeskTool) (created by DeskToolPaneStateSyncer)
    in DeskToolPaneStateSyncer (created by DeskTool)
    in DeskToolFeaturesProvider (created by DeskTool)
    in DeskTool (created by RenderTool)
    in RenderTool (created by SchemaErrorReporter)
    in RouteScope (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in SchemaErrorReporter (created by DefaultLayout)
    in DefaultLayout (created by withRouter(DefaultLayout))
    in withRouter(DefaultLayout) (created by DefaultLayoutRoot)
    in RouterProvider (created by DefaultLayoutRoot)
    in LoginWrapper (created by DefaultLayoutRoot)
    in DefaultLayoutRoot (created by SanityRoot)
    in div (created by SanityRoot)
    in SnackbarProvider (created by SanityRoot)
    in LayerProvider (created by SanityRoot)
    in PortalProvider (created by SanityRoot)
    in UserColorManagerProvider (created by SanityRoot)
    in SanityRoot
    in AppContainer

```

**Comment by dylanjha** [comment]
@danielblignaut can you share your schema code?

In our block content we have a type like this:

```
export default {
  title: 'Block Content',
  name: 'blockContent',
  type: 'array',
  of: [
  // bunch of other types
    {
      type: 'muxUpload',
    },
  ],
}
```

And `muxUpload` is a type we defined like this. You can see this `muxUpload` type contains `mux.video` as a field. And it also contains some other handy fields that we typically need when displaying the video

```
export default {
  name: 'muxUpload',
  title: 'Mux Video',
  type: 'object',
  icon: icon,
  fields: [
    {
      name: 'video',
      title: 'Video file',
      type: 'mux.video',
    },
    {
      name: 'isWide',
      title: 'Wide',
      description: 'Enable this to make the video show extra wide on desktop',
      type: 'boolean',
    },
    {
      name: 'autoplay',
      title: 'Autoplay',
      type: 'boolean',
      validation: Rule =>
        Rule.custom((autoplay, context) => {
          const muxUpload = context.parent
          if (muxUpload.autoplay && !muxUpload.muted) {
            return 'If autoplay is enabled your video must be muted'
          }
          return true
        }),
    },
    {
      name: 'loop',
      title: 'Loop',
      type: 'boolean',
    },
    {
      name: 'controls',
      title: 'Controls',
      type: 'boolean',
    },
    {
      name: 'muted',
      title: 'Muted',
      type: 'boolean',
    },
    {
      name: 'optimizeForVertical',
      title: 'Optimize for vertical',
      description: 'Enable this so styles will optimize for displaying a vertical video',
      type: 'boolean',
    },
    {
      name: 'playbackUrlQueryString',
      title: 'Playback URL Query String',
      description: "Query String to append to your HLS playback URL. Don't include the '?' here.",
      type: 'string',
    },
  ],
```

**Comment by danielblignaut** [comment]
I just tried editting my code to match the above, however I still get the same issue.

block content definition:

```typescript
/**
 * This is the schema definition for the rich text fields used for
 * for this blog studio. When you import it in schemas.js it can be
 * reused in other parts of the studio with:
 *  {
 *    name: 'someName',
 *    title: 'Some title',
 *    type: 'blockContent'
 *  }
 */
export default {
	title: 'Block Content',
	name: 'blockContent',
	type: 'array',
	of: [
		{
			title: 'Block',
			type: 'block',
			// Styles let you set what your user can mark up blocks with. These
			// correspond with HTML tags, but you can set any title or value
			// you want and decide how you want to deal with it where you want to
			// use your content.
			styles: [
				{title: 'Normal', value: 'normal'},
				{title: 'H1', value: 'h1'},
				{title: 'H2', value: 'h2'},
				{title: 'H3', value: 'h3'},
				{title: 'H4', value: 'h4'},
				{title: 'Quote', value: 'blockquote'},
			],
			lists: [
				{title: 'Bullet', value: 'bullet'}
			],
			// Marks let you mark up inline text in the block editor.
			marks: {
				// Decorators usually describe a single property – e.g. a typographic
				// preference or highlighting by editors.
				decorators: [{title: 'Strong', value: 'strong'}, {title: 'Emphasis', value: 'em'}],
				// Annotations can be any object structure – e.g. a link or a footnote.
				annotations: [
					{
						title: 'URL',
						name: 'link',
						type: 'object',
						fields: [
							{
								title: 'URL',
								name: 'href',
								type: 'url'
							}
						]
					}
				]
			}
		},
		// You can add additional types here. Note that you can't use
		// primitive types such as 'string' and 'number' in the same array
		// as a block type.
		{
			type: 'image',
			options: {hotspot: true}
		},
		{
			name: 'table',
			title: 'Table',
			type: 'table'
		},
		{
			name: 'imageSlider',
			title: 'Image Slider',
			type: 'imageSlider'
		},
		{
			name: 'multimedia',
			title: 'Multimedia (audio / video)',
			type: 'muxUpload'
		}
	]
}
```

muxUpload definition:

```typescript
import React from 'react'
import { SanityDefaultPreview } from 'part:@sanity/base/preview'

interface Poster {
	time?: number
	width: number
}

const getPosterSrc = (playbackId: string, { time, width }: Poster) => {
  return `https://image.mux.com/${playbackId}/thumbnail.png?width=${width}&time=${time ||
    1}`
}
const Preview = ({ value }: any) => {
  if (!value) return null
  const { filename, playbackId, thumbTime, status } = value
  if (status === 'ready') {
    return <img src={getPosterSrc(playbackId, { width: 640 })} />
  }
  return (
    <SanityDefaultPreview
      title={filename || playbackId || ''}
      subtitle={status ? `status: ${status}` : null}
    />
  )
}

export default {
  name: 'muxUpload',
  title: 'Mux Video',
  type: 'object',
//   icon: icon,
  fields: [
    {
      name: 'multimedia',
      title: 'Video / Audio file',
      type: 'mux.video',
    },
    // {
    //   name: 'isWide',
    //   title: 'Wide',
    //   description: 'Enable this to make the video show extra wide on desktop',
    //   type: 'boolean',
    // },
    // {
    //   name: 'autoplay',
    //   title: 'Autoplay',
    //   type: 'boolean',
    //   validation: (Rule: any) =>
    //     Rule.custom((autoplay, context) => {
    //       const muxUpload = context.parent
    //       if (muxUpload.autoplay && !muxUpload.muted) {
    //         return 'If autoplay is enabled your video must be muted'
    //       }
    //       return true
    //     }),
    // },
    // {
    //   name: 'loop',
    //   title: 'Loop',
    //   type: 'boolean',
    // },
    // {
    //   name: 'controls',
    //   title: 'Controls',
    //   type: 'boolean',
    // },
    // {
    //   name: 'muted',
    //   title: 'Muted',
    //   type: 'boolean',
    // },
    // {
    //   name: 'optimizeForVertical',
    //   title: 'Optimize for vertical',
    //   description: 'Enable this so styles will optimize for displaying a vertical video',
    //   type: 'boolean',
    // },
    // {
    //   name: 'playbackUrlQueryString',
    //   title: 'Playback URL Query String',
    //   description: "Query String to append to your HLS playback URL. Don't include the '?' here.",
    //   type: 'string',
    // },
  ],
  preview: {
    select: {
      playbackId: 'video.asset.playbackId',
      status: 'video.asset.status',
      duration: 'video.asset.data.duration',
      thumbTime: 'video.asset.thumbTime',
      filename: 'video.asset.filename',
    },
    component: Preview,
  },
}

```

**Comment by danielblignaut** [comment]
The error occurs specifically on clicking the edit button below:

<img width="648" alt="Screenshot 2021-02-10 at 17 17 17" src="https://user-images.githubusercontent.com/1087177/107546098-e59d0600-6bc3-11eb-890f-3e6d106614db.png">

**Comment by dylanjha** [comment]
@danielblignaut I was able to repro this. Will have a look. Thanks for reporting

**Comment by danielblignaut** [comment]
no problem - I would try and resolve myself but a bit of a sanity newbie! Thanks for the help
