### ISSUE TITLE
Malformed asset error with Sanity 2.10.0

### ISSUE THREAD

**Issue by simonandywilson** [sanity-io/sanity-plugin-mux-input#29]
After upgrading to Sanity 2.10.0, uploading an asset using this plugin causes Sanity to crash with the following error:

```
Error: Malformed asset _ref 'c77166f1-da6a-478f-9c9e-d747de8dbcf2'. Expected an id like "image-Tb9Ew8CXIwaY6R1kjMvI0uRR-2000x3000-jpg".
    at parseAssetId (/static/js/app.bundle.js:91740:13)
    at urlForImage (/static/js/app.bundle.js:91870:17)
    at ImageUrlBuilder.url (/static/js/app.bundle.js:92285:14)
    at http://localhost:3333/static/js/app.bundle.js:91545:124
    at DefaultPreview.render (/static/js/app.bundle.js:125438:39)
    at finishClassComponent (/static/js/vendor.bundle.js:20318:31)
    at updateClassComponent (/static/js/vendor.bundle.js:20268:24)
    at beginWork (/static/js/vendor.bundle.js:21778:16)
    at HTMLUnknownElement.callCallback (/static/js/vendor.bundle.js:3346:14)
    at Object.invokeGuardedCallbackDev (/static/js/vendor.bundle.js:3395:16)
```

**Comment by ktisakib** [comment]
I got the same probleeem can   aan one help here??

**Comment by rohityellapu** [comment]
Got the same problem can anyone help?

**Comment by stipsan** [comment]
If you're able to create a reproduction repository and share it with us I'll take a look 🙂 You don't need to provide a Sanity Project ID and dataset, nor Mux API Credentials.

From the face of it the errors indicate it could be related to how preview thumbnails are setup in the Studio, so it'll be useful to know how the Schema is setup 🤔

**Comment by jzhao-30** [comment]
Same problem, any solutions?

**Comment by panrosk** [comment]
Just had the same error. Is there any workaround.

**Comment by R-Delfino95** [comment]
Hi!
We are no longer supporting Sanity v2.
We recommend upgrading to the latest version of the plugin ([v2.14.0](https://github.com/sanity-io/sanity-plugin-mux-input/releases/tag/v2.14.0)) and updating Sanity Studio to v5 (or v3 and above). In those versions, there are no issues when uploading assets.

Let us know if you have any questions during the upgrade process!
