### ISSUE TITLE
MUX plugin crashes Sanity's new Typegen script

### ISSUE THREAD

**Issue by mklasinc** [sanity-io/sanity-plugin-mux-input#359]
**Describe the bug**

MUX video plugin crashes Sanity's new [Typegen script](https://www.sanity.io/docs/sanity-typegen) script, which prevents Sanity users from using the Typegen feature on projects using the MUX plugin.

**To Reproduce**

1. Include the MUX plugin in `sanity.config.ts` and add a MUX input field to one of the document schemas
2. run `npx sanity schema extract` in the terminal
3. The script should throw the following TypeError
```
✖ Failed to extract schema

TypeError: Failed to load configuration file "/Users/miha.klasinc/Documents/GitHub/portfolio/sanity.config.ts":
l.matchMedia is not a function
    at jo (~/Documents/GitHub/portfolio/node_modules/@mux/mux-player/dist/index.cjs.js:145:8374)
    at Object.<anonymous> (~/Documents/GitHub/portfolio/node_modules/@mux/mux-player/dist/index.cjs.js:145:8586)
    at Object.newLoader [as .js] (~/Documents/GitHub/portfolio/node_modules/sanity/node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (~/Documents/GitHub/portfolio/node_modules/sanity/node_modules/esbuild-register/dist/node.js:4838:24)
```

**Expected behavior**

Type generation script should complete without issues and correctly extract project schemas, including for MUX video inputs.

**Which versions of Sanity are you using?**

```
@sanity/cli (global)  3.37.2 (up to date)
@sanity/icons         2.11.8 (up to date)
@sanity/image-url      1.0.2 (up to date)
@sanity/types         3.37.2 (up to date)
@sanity/ui             2.1.2 (latest: 2.1.3)
@sanity/vision        3.27.1 (latest: 3.37.2)
sanity                3.37.2 (up to date)
```

**What operating system are you using?**
Mac

**Which versions of Node.js / npm are you running?**

```
10.2.4
v20.11.1
```

**Comment by michaelcpuckett** [comment]
+1

**Comment by 14850842** [comment]
+1

**Comment by sgulseth** [comment]
Thanks for reporting. A fix for this will be part of the next release, which should happen next week,

**Comment by mklasinc** [comment]
Super, thanks for the awesome work in creating and maintaining this plugin!

**Comment by sgulseth** [comment]
@diboune It should come out later today!

**Comment by sgulseth** [comment]
Released https://github.com/sanity-io/sanity/releases/tag/v3.40.0
